version: "3.8"
services:
  web:
  #we have used build . to get the latest image from jenkins pipeline
    # Now as we have given our Dockerhub credentials so image can now be build from Dockerhub
    # build: .               
    image: raeel/flask-app:latest 
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
